name: Build image from release tag

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: prepare package
        run: |
          mkdir -p .debpkg/usr/bin
          cp src/metal-bootloader.sh .debpkg/usr/bin/metal-bootloader.sh
          chmod +x .debpkg/usr/bin/metal-bootloader.sh
          mkdir -p .debpkg/etc/systemd/system
          cp src/metal-bootloader.service .debpkg/etc/systemd/system/metal-bootloader.service

          # create DEBIAN directory if you want to add other pre/post scripts
          mkdir -p .debpkg/DEBIAN
          cp src/postinst .debpkg/DEBIAN/postinst
          chmod +x .debpkg/DEBIAN/postinst
      - uses: jiro4989/build-deb-action@v2
        with:
          package: metal-bootloader
          package_root: .debpkg
          maintainer: MetalStack
          version: ${{ github.ref }} # refs/tags/v*.*.*
          arch: 'amd64'
          depends: 'libc6 (>= 2.2.1), git'
          desc: 'metal-stack bootloader.'
